FROM node:12

RUN mkdir -p /usr/src/app && \
    chown -R node:node /usr/src/app

WORKDIR /usr/src/app

RUN apt update && \
    apt install -y zip && \
    rm -rf /var/lib/apt/lists/*

COPY --chown=node:node . .

USER node

RUN npm install && npm run build

RUN zip -r dist.zip dist
