export const environment = {
  production: true,
  name: (window as { [key: string]: any })['env']['name'] || '',
  sitePath: 'mdo.karmayogiprod.nic.in',
  karmYogiPath: 'https://karmayogiprod.nic.in',
  cbpPath: 'https://cbp.karmayogiprod.nic.in',
  portalRoles: (((window as { [key: string]: any })['env']['portalRoles'] || '').split(',')) || [],
  contentHost: (window as { [key: string]: any })['env']['contentHost'] || '',
  contentBucket: (window as { [key: string]: any })['env']['azureBucket'] || '',
  userBucket: (window as { [key: string]: any })['env']['userBucket'] || '',
  domainName: (window as { [key: string]: any })['env']['domainName'] || '',
  mdoPath: (window as { [key: string]: any })['env']['mdoPath'] || '',
  resendOTPTIme: (window as { [key: string]: any })['env']['resendOTPTIme'] || 120,
  teamsUrl: (window as { [key: string]: any })['env']['teamsUrl'] || '',
  connectionType: (window as { [key: string]: any })['env']['connectionType'] || '',
  KCMframeworkName: (window as { [key: string]: any })['env']['KCMframeworkName'] || '',
  ODCSMasterFramework: (window as { [key: string]: any })['env']['ODCSMasterFramework'] || '',
  compentencyVersionKey: (window as { [key: string]: any })['env']['compentencyVersionKey'] || '',
  doptOrg: (window as { [key: string]: any })['env']['doptOrg'] || '',
  dicussV2Bucket: (window as { [key: string]: any })['env']['dicussV2Bucket'] || '',
  portalsForNotifications: (((window as { [key: string]: any })['env']['portalsForNotifications'] || {})) || {},
  googleStorageUrl: (window as { [key: string]: any })['env']['googleStorageUrl'] || '',
  mdoChannelsBookmarkId: (window as { [key: string]: any })['env']['mdoChannelsBookmarkId'] || '',
  spvorgID: (window as { [key: string]: any })['env']['spvorgID'] || '',
  azureHost: (window as { [key: string]: any })['env']['azureHost'] || '',
  azureBucket: (window as { [key: string]: any })['env']['azureBucket'] || '',
  azureOldHost: (window as { [key: string]: any })['env']['azureOldHost'] || '',
  azureOldBuket: (window as { [key: string]: any })['env']['azureOldBuket'] || '',
  assessmentBuffer: (window as { [key: string]: any })['env']['assessmentBuffer'] || 0,
  quizResultTimeout: (window as { [key: string]: any })['env']['quizResultTimeout'] || 0,
  publicContentSurveyId: (window as { [key: string]: any })['env']['publicContentSurveyId'] || 0,
}
